# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Robert Max Rees
tagline:          A Code Blog
url:              http://robertmaxrees.github.io
paginate:         3
baseurl:          /
author:
  name:           Robert Max Rees
  url:            https://twitter.com/robertmaxrees
  email:          robertmaxrees@gmail.com

# Custom vars
version:          1.0.0
